baseURL = "https://lukeraybould.dev/"
languageCode = 'en-gb'
title = 'lraybould'
theme = 'console'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  description = "Personal website for blog posts"
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Posts"
  url = "/posts/"

[[params.navlinks]]
  name = "Photos"
  url = "/photos/"